### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'warn'

### ISSUE THREAD

**Issue by cdeil** [cds-astro/ipyaladin#1]
@tboch - I'm getting this error:
https://github.com/cdeil/hipsperiments/blob/master/ipyal_bool_error.ipynb

Note that this is without the extension activated, so maybe it's my fault?

Or is this a bug where you accidentally clobber the `log` property and should better choose another name for your property?
```
class Aladin(widgets.DOMWidget):
    log = Bool(True).tag(sync=True, o=True)
 ```

**Comment by tboch** [comment]
Disclaimer: we started getting familiar with widgets quite recently, I'm not an expert at all.

My understanding is that without activating the extension, this is expected. I get the same error when not activated.
Did you manage to make it work once the extension is activated?

**Comment by christinahedges** [comment]
I have the same error, I followed your install instructions and turned on both extensions with:

`jupyter nbextension enable --py widgetsnbextension`
`jupyter nbextension enable --py --sys-prefix ipyaladin`

and I get the same issue.

**Comment by tboch** [comment]
can you check with the following code whether you can display simple widgets:
```python
from ipywidgets import widgets
widgets.IntSlider(
    value=7,
    min=0,
    max=10,
    step=1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
```

**Comment by christinahedges** [comment]
I get the following error:

`Error rendering Jupyter widget. Widget not found: {"model_id":"b9825337cd7946cc8dc3343a6623f234"}`

**Comment by tboch** [comment]
Can you check ipywidgets and widgetsnbextension versions?

```python
import ipywidgets
ipywidgets.__version__

import widgetsnbextension
widgetsnbextension.__version__
```

**Comment by christinahedges** [comment]
`ipywidgets` is version 6.0.0
`widgetsnbextension` is version 3.0.1

**Comment by christinahedges** [comment]
Updating these fixes the problem. Beautiful widget now works! Thanks for troubleshooting for me

**Comment by cdeil** [comment]
@tboch - Close this issue? Or is there a way to improve something, i.e. to give an error message that says "You need to activate this extension, see ... for help" instead of an AttributeError?

**Comment by bmatthieu3** [comment]
I close the issue as activating the extension is not needed anymore from version 0.1.11
