### ISSUE TITLE
does not work in google colab?

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/ipyaladin#112]
Have report from users that we might have issues in colab, this is just a reminder to check

**Comment by tboch** [comment]
Do you have more details? 0.4.0 seems to work fine on colab, I managed to run 02_Base_Commands.ipynb (except the *add_fits* part, but this seems to be a different issue, not related to colab)

**Comment by ManonMarchand** [comment]
It was a report from an astronomer at IAU, I cannot reproduce neither. It works just fine on my computer too.

Did you get a specific error message with `add_fits`?

**Comment by tboch** [comment]
It seems the version I installed in colab (0.4.0) did not support `add_fits`. The message I got is:

```AttributeError: 'Aladin' object has no attribute 'add_fits'```

**Comment by ManonMarchand** [comment]
Hum yes. The examples are for the current master and not for the latest version. This is not user friendly. Maybe we should start developing in a "develop" branch?
