### ISSUE TITLE
ipyaladin viewer style sheet issue in marimo notebooks

### ISSUE THREAD

**Issue by pgriffin17** [cds-astro/ipyaladin#113]
I am attempting to use ipyaladin in [marimo](https://github.com/marimo-team/marimo) - a newer python notebook. They have native support for AnyWidget so I thought it would be fun to try ipyaladin in marimo. However, I ran into an issue that the icons for the widget appeared huge and did not appear on the image visualization. The area that registers clicks was also directly below the image. See screenshot for an idea of what's going on - the screenshot is at 30% zoom in my browser.

In sharing this with the marimo team, it is thought to be a style sheet issue - "We render the widgets in a ShadowDOM while jupyter does not, so it could be they aren’t compatible with shadow doms". This issue will also be posted to marimo's repo.

![image](https://github.com/user-attachments/assets/cb2d1e6e-1ccc-4c59-b9d4-b07c43c2815a)

Code to reproduce:

```python
import marimo

__generated_with = "0.8.2"
app = marimo.App(width="full")


@app.cell
def __():
    import marimo as mo
    from ipyaladin import Aladin
    return Aladin, mo


@app.cell
def __(Aladin, mo):
    aladin = Aladin(target="ngc4151", fov=2)
    aladin = mo.ui.anywidget(aladin)
    aladin
    return aladin,


if __name__ == "__main__":
    app.run()
```

**Comment by ManonMarchand** [comment]
Hello, 
Just learned about shadow doms ^^'
We'll try to support this, Marimo notebooks are super cool. But there's a bit of reading and learning on my side before. Maybe @tboch or @bmatthieu3 have an idea on how to proceed?

**Comment by ManonMarchand** [comment]
We should do a release around September 20, but you can also try with the unreleased version if you want. The installation instructions are here https://cds-astro.github.io/ipyaladin/getting_started/getting_started.html#unreleased-version
