### ISSUE TITLE
requests became mandatory with planetary name support 

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/ipyaladin#117]
We have to make it optional or add it officially in our dependencies, see failure of conda forge package 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1031951&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d 

https://github.com/conda-forge/ipyaladin-feedstock/pull/16

TODO : add CI without optional dependencies

**Comment by tboch** [comment]
Well, we could also remove requests dependency and replace the code with `urllib.request` calls.

Having an additional dependency just for this feel weird to me.
