### ISSUE TITLE
Document that ipyaladin "works with" Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [cds-astro/ipyaladin#119]
Hi

I've gotten some example working with ipyaladin and Panel.

**Would you be interested in documenting this?** This could help users build tools with ipyaladin and share them with friends, colleagues or the world.

For example in a new section in the README called "Works With" or "Ecosystem" and then a link to for example this Hugging Face space https://huggingface.co/spaces/awesome-panel/aladin?

https://github.com/user-attachments/assets/d69ec211-c962-4033-93f5-e194ab62cb4e

or maybe by documenting a minimal example?

```python
import panel as pn
from ipyaladin import Aladin

pn.extension("ipywidgets")

aladin = Aladin(
    target="159.2135528 -58.6241989",
    survey="https://alasky.u-strasbg.fr/Planets/Mars_Viking_MDIM21",
    fov=10,
    height=800,
)
pn.panel(aladin, sizing_mode="stretch_width").servable()
```

- [x] I would be interested in making the PR.

**Comment by MarcSkovMadsen** [comment]
FYI. If there is ever an interest in creating a Panel native widget its relatively straightforward. The only difference is use of traitlets and param libraries. The AnyWidget Javascript can be used unchanged.

See https://panel.holoviz.org/reference/custom_components/AnyWidgetComponent.html

**Comment by ManonMarchand** [comment]
Done, thanks for the suggestion :slightly_smiling_face:
