### ISSUE TITLE
JupyterLab build fails with recent JL

### ISSUE THREAD

**Issue by athornton** [cds-astro/ipyaladin#12]
With Jupyterlab 0.32.1, at least, I get:

```

    ERROR in ./src/jupyter-aladin.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./jquery-3.0.0.min.js in /Users/adam/git/ipyaladin/js/src
     @ ./src/jupyter-aladin.js 11:13-45
```

oddly the build process keeps going, but then jupyter labextension enable fails.

**Comment by athornton** [comment]
The jquery that gets installed is https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz

**Comment by athornton** [comment]
Even once the incorrect hardcoding is fixed, and the module version numbers updated to 1.4, I still get: 

```
Uncaught (in promise) Module ipyaladin, semver range 0.1.4 is not registered as a widget module
```

Despite the fact that the labextension is installed and enabled.

Commit `aa009c6d88ccfd2d25ea9d2b08c9dda201b9f55a` still works fine.  So something broke between then and now.  I'll try some bisection tomorrow.

**Comment by athornton** [comment]
Here's what I get after bisection:

```
(ipyaladin) adam@ixitxachitl:~/git/ipyau/ipyaladin$ git bisect bad
9d7b727c1a55ae72075c705ae13662a8a8351f1e is the first bad commit
commit 9d7b727c1a55ae72075c705ae13662a8a8351f1e
Author: Thomas Boch <thomas.boch@gmail.com>
Date:   Mon Jun 11 11:52:15 2018 +0200

    Add 'select' listener, and rectangular_selection method

    Rectanguler selection can now be triggered and the list of sources in
    the selection retrieved in the Python code

:040000 040000 30c01679518f4f6fa8a67cedea674b1f99ef198c cf57966c3bce501a6dfdff099835d35a7dc2ad1d M	examples
:040000 040000 aa5d1c8b57eace9d019d3e828dc5ba7e4f9f28dc 2def077d2992e008d52f2dec063bcb3d7c7e4a7f M	ipyaladin
:040000 040000 3f20cb579b6199a6016c00c963a1a35a39e84afa e05eb73d7a2a72e034eebcfb9e2d5d4c410a6e51 M	js
```

**Comment by tboch** [comment]
Thank you for having a look at this. This should be fixed in f2fdb79457d9ca4943656cc2c8a5bb06ccfb3c69
The view and model version were not matching the one declared in package.json

Could you try again?

**Comment by athornton** [comment]
I will give it a shot either today or tomorrow, thanks.

**Comment by athornton** [comment]
At `e95aa0632fc1a82a1cc985227410854ebb22713e` I get `Error displaying widget
renderer.js:97 Module ipyaladin, semver range 0.1.4 is not registered as a widget module`; the build works fine now, though.

**Comment by tboch** [comment]
apologies, I was testing in the wrong environment.
f737b76b371cc415f7835f9e6ef8b1eeaffeed0a fixes the problem for me

**Comment by athornton** [comment]
It works for me as well.  I think this one can be closed.  Thanks!

**Comment by tboch** [comment]
Great, thank you for reporting this.
