### ISSUE TITLE
JS error in JupyterLab

### ISSUE THREAD

**Issue by jovenitti** [cds-astro/ipyaladin#123]
When trying to run the following code in a notebook

`from ipyaladin import Aladin`
`aladin = Aladin()`
`aladin`

I get the following error:

`[Open Browser Console for more detailed log - Double click to close this message]`
`Failed to load model class 'AnyModel' from module 'anywidget'`
`Error: No version of module anywidget is registered`
`    at f.loadClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:74856)`
`    at f.loadModelClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:10729)`
`    at f._make_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7517)`

From Jupyter Lab v3.5.2 (Jupyter Server 2.5.0).
anywidget version 0.9.2

Note that using VSCode (with the same jupyter kernel) it works.

**Comment by ManonMarchand** [comment]
Hi! :slightly_smiling_face: 

I think this was solved in anywidget here https://github.com/manzt/anywidget/pull/553 . It didn't work with jupyterlab 3 before

So you have two solutions: 
- either upgrade jupyterlab to version 4
- or upgrade anywidget to a version more recent than this commit (at least 0.9.10)

Hope this works

**Comment by ManonMarchand** [comment]
Do you still have issues?

**Comment by jovenitti** [comment]
Amazing! Installed anywidget 0.9.13 and now it works.
Thank you very very much!
..happy to explore ipyaladin :)
