### ISSUE TITLE
Shape is not working in add_markers

### ISSUE THREAD

**Issue by zhouconghao** [cds-astro/ipyaladin#129]
`aladin.add_markers(markers, color="red", shape="plus", source_size=8)`

It is always a circle for some reason. I tested on VSCode Jupyter and on Binder with the basic example.

**Comment by ManonMarchand** [comment]
Hi! Sorry for the delay (holiday time here)

Indeed, that's a bug, thanks for reporting it

**Comment by zhouconghao** [comment]
Thanks!
