### ISSUE TITLE
cutout and save the current Aladin view as a FITs image with WCS

### ISSUE THREAD

**Issue by havok2063** [cds-astro/ipyaladin#15]
It would be cool to be able to save a cutout of a specified size of the current view in Aladin as a FITS image that contains the WCS information.  One could then overlay this image on any other image data.  

or alternatively, using the `get_JPEG_thumbnail` method that currently exists, to save the JPEG image but embed the WCS info into the image header, so the JPEG itself can be overplayed elsewhere.

**Comment by tboch** [comment]
We will add a get_view_WCS() (and a get_dimensions()) method to retrieve an Astropy WCS object for the current view
