### ISSUE TITLE
Support basic astropy-regions SkyRegion

### ISSUE THREAD

**Issue by tboch** [cds-astro/ipyaladin#16]
See https://astropy-regions.readthedocs.io/en/latest/shapes.html for detailed description of regions.
Would be nice to have at least for a start PointSkyRegion;, CircleSkyRegion, RectangleSkyRegion, LineSkyRegion and TextSkyRegion

**Comment by bmatthieu3** [comment]
There is also the support of EllipseSkyRegion in regions and Aladin Lite so a wrapper may be possible for it as well
