### ISSUE TITLE
JupyterLab 1.0 support

### ISSUE THREAD

**Issue by martinRenou** [cds-astro/ipyaladin#17]
JupyterLab 1.0 is released, and ipywidgets 7.5. For ipyaladin to work with those new versions you would need to make the following change in the `package.json` file:
`"@jupyter-widgets/base": "^1.1",` becomes `"@jupyter-widgets/base": "^1.1 || ^2.0",`

**Comment by athornton** [comment]
As you do this, could you please publish a version of the Jupyterlab widget to npm?  It would be convenient to be able to install it with `jupyter labextension install` rather than having to check out the git repository and then do an install from the directory.

**Comment by athornton** [comment]
I've built a PR for it:

https://github.com/cds-astro/ipyaladin/pull/18

**Comment by athornton** [comment]
Except that it fails to build with `jupyter lab build`.  I'll investigate.

**Comment by bmatthieu3** [comment]
Hi @athornton , can you upgrade to ipyaladin 0.1.11 ? jupyterlab is supported now
