### ISSUE TITLE
Upload local FITS image

### ISSUE THREAD

**Issue by tboch** [cds-astro/ipyaladin#21]

**Comment by informationcake** [comment]
I couldn't find a way to do this either, so if it is currently not possible I'd love to see this implemented. Can one load local fits files in? target='some_local_path' would be great

**Comment by bmatthieu3** [comment]
To add a description of what this could look like: load an astropy fits image hdu returning a `Image` object ipyaladin.add_fits_hdu(my_hdu)

The `Image` could have similar methods as `ImageSuryey` to set the colormap, opacity, stretch...

**Comment by ManonMarchand** [comment]
Fixed by #86
