### ISSUE TITLE
update the documentation to extract images

### ISSUE THREAD

**Issue by ShrutikaSingh** [cds-astro/ipyaladin#22]

**Comment by tboch** [comment]
Hi @ShrutikaSingh , could you elaborate a bit your request?
Thanks!

**Comment by ShrutikaSingh** [comment]
there is no proper documentation other than the examples for knowing the different attributes of the function, even the GitHub README.md has very limited information. Can you please update the documentation, so that it could be understandable by all?

**Comment by tboch** [comment]
agreed, I have to improve the documentation. 
I was asking specifically what you meant by _extracting images_.

**Comment by ShrutikaSingh** [comment]
other than the function aladin.get_JPEG_thumbnail() which opens the image in a new window... I wanted to download an image.. so I needed a function for that.. I don't know if there is a function for that already... could you please guide me regarding this issue?

**Comment by ShrutikaSingh** [comment]
I was looking for a function because I was requiring a huge number of images to download also the data type of the JPEG_thumbnail is NoneType so I was unable to use the Pillow library

**Comment by ShrutikaSingh** [comment]
hey bumbing up the issue incase you forgot...could you please help me out?

**Comment by ManonMarchand** [comment]
Linked to #24

**Comment by ManonMarchand** [comment]
will be done with #15
