### ISSUE TITLE
Can I use ipyaladin in Google Colab?

### ISSUE THREAD

**Issue by ale-munozarancibia** [cds-astro/ipyaladin#23]
I've tried using ipyaladin in a jupyter notebook with

!pip install ipyaladin
!jupyter nbextension enable --py widgetsnbextension
!jupyter nbextension enable --py --sys-prefix ipyaladin

but the last line doesn't work in Google Colab. Is there an alternative to this code?

**Comment by tboch** [comment]
Good question, I don't know Google Colab at all, but I'm going to investigate. Keep tuned.
Thank you for your interest!

**Comment by ggreco77** [comment]
It could be very useful to fix it. I copy the output from  Colaboratory:

`!python --version`
Python 3.7.10

`!pip install ipyaladin`
`!jupyter nbextension enable --py widgetsnbextension`
`!jupyter nbextension enable --py --sys-prefix ipyaladin`

Requirement already satisfied: ipyaladin in /usr/local/lib/python3.7/dist-packages (0.1.7)
Requirement already satisfied: ipywidgets>=6.0.0 in /usr/local/lib/python3.7/dist-packages (from ipyaladin) (7.6.3)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=6.0.0->ipyaladin) (5.5.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=6.0.0->ipyaladin) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=6.0.0->ipyaladin) (5.1.2)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=6.0.0->ipyaladin) (4.10.1)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=6.0.0->ipyaladin) (5.0.5)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=6.0.0->ipyaladin) (1.0.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (2.6.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (54.1.2)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.8.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (1.0.18)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (4.4.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (4.8.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (5.3.1)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (4.7.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (2.6.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (0.2.0)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (5.1.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (5.3.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.7.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (5.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (2.11.3)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.5.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.9.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (2.8.1)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (22.0.3)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.4.3)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.4.4)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.8.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (3.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.7.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.1.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (20.9)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (2.4.7)
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named ipyaladin

**Comment by ameliabayo** [comment]
In case it helps, I solved the part of jupyter looking for extensions in the "wrong place" (python2.7/dist-packages) the following way:
#get versions >6 tornado and the client
!pip install tornado --upgrade
!pip install jupyter-client --upgrade

!pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
!jupyter contrib nbextension install --user

!pip install ipyaladin

!jupyter nbextension enable --py widgetsnbextension
!jupyter nbextension enable --py --sys-prefix ipyaladin

With that I got no errors, and if I list the nbextensions, ipyaladin appears as "OK" (validated)

Unfortunately when I call aladin, I still do not get the widget :-(

**Comment by bmatthieu3** [comment]
From the new version 0.1.11, ipyaladin does not seem to need these 2 lines anymore:

!jupyter nbextension enable --py widgetsnbextension
!jupyter nbextension enable --py --sys-prefix ipyaladin

It might be interesting to retest on your side with ipyaladin upgraded. Let me know what is the outcome, thanks very much

**Comment by ggreco77** [comment]
I tested the new version in Google Colab [here](https://colab.research.google.com/drive/1FuIy4FnVM-dPG84nWBwMyt0FBBEVFpPA?usp=sharing).  Although there is support from Google Colab for the Third-party Jupyter widgets ; the ipyladin widgets are not displayed

**Comment by bmatthieu3** [comment]
Hi @ggreco77 
I found that external jupyter widgets (such as ipyaladin) from ipywidgets need a little snippet of code after importing ipyaladin.

```
from google.colab import output
output.enable_custom_widget_manager()
```

By doing this, it works for me:

<img width="1512" alt="Capture d’écran 2022-12-06 à 15 55 56" src="https://user-images.githubusercontent.com/2772384/205947371-fd98c438-fd0c-42fc-8edc-2214de7811cd.png">

**Comment by ggreco77** [comment]
Got it; it works perfectly.
thanks!

**Comment by ManonMarchand** [comment]
Yup, perfect here too. I guess you can close this issue :)
