### ISSUE TITLE
Add method to save current view

### ISSUE THREAD

**Issue by tboch** [cds-astro/ipyaladin#24]
**Description of the new feature**

Add a method _save_view_ to save the current view as an image associated to a table listing the X,Y positions of the catalogue sources currently displayed.
The image could be given as a 3-dimensional numpy array, the table as an Astropy Table object.

This is similar to the Aladin Desktop feature available from _File-->Save the current view-->PNG+LINK_

**Comment by ManonMarchand** [comment]
linked to #15
