### ISSUE TITLE
Error: Module ipyaladin, semver range 0.1.7 is not registered as a widget module

### ISSUE THREAD

**Issue by JosephKarpinski** [cds-astro/ipyaladin#27]
Python 3.8.5

VisualStudio Python VSCode

Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

!jupyter nbextension enable --py --sys-prefix ipyaladin

Enabling notebook extension ipyaladin/extension...
      - Validating: OK

import ipyaladin as ipyal

aladin= ipyal.Aladin(target='messier 51', fov=1)
aladin

Error: Module ipyaladin, semver range 0.1.7 is not registered as a widget module

**Comment by JosephKarpinski** [comment]
pip3 install ipyaladin
Collecting ipyaladin
  Downloading ipyaladin-0.1.7.tar.gz (433 kB)
     |████████████████████████████████| 433 kB 882 kB/s 
Requirement already satisfied: ipywidgets>=6.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipyaladin) (7.6.3)
Requirement already satisfied: nbformat>=4.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=6.0.0->ipyaladin) (5.0.8)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=6.0.0->ipyaladin) (1.0.0)
Requirement already satisfied: traitlets>=4.3.1 in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=6.0.0->ipyaladin) (5.0.5)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=6.0.0->ipyaladin) (7.19.0)
Requirement already satisfied: ipykernel>=4.5.1 in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=6.0.0->ipyaladin) (5.3.4)
Requirement already satisfied: widgetsnbextension~=3.5.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=6.0.0->ipyaladin) (3.5.1)
Requirement already satisfied: ipython-genutils in ./opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (3.2.0)
Requirement already satisfied: jupyter-core in ./opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (4.6.3)
Requirement already satisfied: pygments in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (2.7.2)
Requirement already satisfied: backcall in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.2.0)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (4.8.0)
Requirement already satisfied: setuptools>=18.5 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (54.1.2)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.1.0)
Requirement already satisfied: decorator in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (4.4.2)
Requirement already satisfied: jedi>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.17.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (3.0.8)
Requirement already satisfied: pickleshare in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.7.5)
Requirement already satisfied: jupyter-client in ./opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (6.1.7)
Requirement already satisfied: tornado>=4.2 in ./opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (6.0.4)
Requirement already satisfied: notebook>=4.4.1 in ./opt/anaconda3/lib/python3.8/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (6.1.4)
Requirement already satisfied: attrs>=17.4.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (0.17.3)
Requirement already satisfied: six>=1.11.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=6.0.0->ipyaladin) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in ./opt/anaconda3/lib/python3.8/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.6.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.7.0)
Requirement already satisfied: wcwidth in ./opt/anaconda3/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=6.0.0->ipyaladin) (0.2.5)
Requirement already satisfied: python-dateutil>=2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (2.8.1)
Requirement already satisfied: pyzmq>=13 in ./opt/anaconda3/lib/python3.8/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=6.0.0->ipyaladin) (19.0.2)
Requirement already satisfied: argon2-cffi in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (20.1.0)
Requirement already satisfied: nbconvert in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (6.0.7)
Requirement already satisfied: Send2Trash in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.5.0)
Requirement already satisfied: prometheus-client in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.8.0)
Requirement already satisfied: terminado>=0.8.3 in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.9.1)
Requirement already satisfied: jinja2 in ./opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (2.11.2)
Requirement already satisfied: cffi>=1.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.14.3)
Requirement already satisfied: testpath in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.4.4)
Requirement already satisfied: jupyterlab-pygments in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.1.2)
Requirement already satisfied: entrypoints>=0.2.2 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.4.3)
Requirement already satisfied: defusedxml in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.6.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.5.1)
Requirement already satisfied: mistune<2,>=0.8.1 in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.8.4)
Requirement already satisfied: bleach in ./opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (3.2.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./opt/anaconda3/lib/python3.8/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.1.1)
Requirement already satisfied: pycparser in ./opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (2.20)
Requirement already satisfied: async-generator in ./opt/anaconda3/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.10)
Requirement already satisfied: nest-asyncio in ./opt/anaconda3/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (1.4.2)
Requirement already satisfied: packaging in ./opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (20.4)
Requirement already satisfied: webencodings in ./opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=6.0.0->ipyaladin) (2.4.7)
Building wheels for collected packages: ipyaladin
  Building wheel for ipyaladin (setup.py) ... done
  Created wheel for ipyaladin: filename=ipyaladin-0.1.7-py2.py3-none-any.whl size=869746 sha256=28ec95777b478461133cf2ab97cc08a6e5e624a1d701e3aed4b5ce964cca8c0b
  Stored in directory: /Users/josephkarpinski/Library/Caches/pip/wheels/c7/5d/02/5283ed6a8f6d47ca9e9620e0859407594f6e71dddbe1b9afc5
Successfully built ipyaladin
Installing collected packages: ipyaladin
Successfully installed ipyaladin-0.1.7

**Comment by bmatthieu3** [comment]
I close the issue, as it seems to have been resolved from the last version. Do not hesitate to reopen a new one if the problem still persist on your side
