### ISSUE TITLE
jupyterlab not showing example 

### ISSUE THREAD

**Issue by Grindayzer** [cds-astro/ipyaladin#28]
Hi
How to to fix this issue please in jupyterlab :
```
import ipyaladin
print (ipyaladin.__version__)
```
0.1.7
```
import ipywidgets
print (ipywidgets.__version__)
```
7.6.3

```
import ipyaladin as ipyal
aladin= ipyal.Aladin(target='messier 51', fov=1)
aladin
```

I don't have a view, but this just this line 
`Aladin(fov=1.0, options=['allow_full_zoomout', 'coo_frame', 'fov', 'full_screen', 'log', 'overlay_survey', 'ov…`

Thank's
G

**Comment by bmatthieu3** [comment]
Let me know if you still have the issue after upgrading to the 0.1.11 version. For now, I will close the issue.
