### ISSUE TITLE
miss XMM image

### ISSUE THREAD

**Issue by rhuang-astro** [cds-astro/ipyaladin#29]
Awesome project!

But I can't show XMM image.

```
aladin= ipyal.Aladin(survey= 'P/XMM/EPIC' ,target=f'M31', fov=3/60.)
aladin
```

**Comment by bmatthieu3** [comment]
I think that the ID changed for that survey: "P/XMM/EPIC-RGB" seems to work, so I close that issue

**Comment by bmatthieu3** [comment]
Here is a list of survey you should have access to: https://aladin.u-strasbg.fr/hips/list
