### ISSUE TITLE
Enabling widgetsnbextension and ipyaladin after installation

### ISSUE THREAD

**Issue by koeppeda** [cds-astro/ipyaladin#30]
This is not really an issue with the application itself, but how to get it working initially.

In the README section that lists the terminal commands to enable the application, I believe these two lines are incorrect (for python3):

$ jupyter nbextension enable --py widgetsnbextension
$ jupyter nbextension enable --py --sys-prefix ipyaladin

There should be a hyphen between jupyter and nbextension (jupyter-nbextension).  When I was installing, I had trouble because running these lines would only call "jupyter" and then try to open a notebook with the name "nbextension".  I finally realized this when I went into the binary directory and saw some names are now hyphenated.  

I don't know if anyone else has had trouble with this, but I thought I'd put it out there.  Hope this helps!

**Comment by bmatthieu3** [comment]
Since version 0.1.11, these two lines are not needed anymore after pip installing ipyaladin (it has been tested on a new created  python environment).
