### ISSUE TITLE
Ipyaladin fails to load in MyBinder

### ISSUE THREAD

**Issue by stvoutsin** [cds-astro/ipyaladin#32]
**Description:**
Ipyaladin example notebooks do not produce an Aladin visualization widget, instead the output is just a print out of the Aladin object in text. When checking the console, it seems that there are some errors, which are listed below.
This has been tested  in MyBinder, using the Binder link in the repo description.

**Notebook:**
`1_Getting_Started.ipynb
`

**Web Console Stack trace:**
```
The resource from “https://hub.gke2.mybinder.org/user/cds-astro-ipyaladin-9hhl4ryr/static/ipyaladin.js?v=20220505114547” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Could not instantiate widget
```

**Browsers Tested:**

- Chrome (Version 99.0.4844.51 (Official Build) (64-bit))
- Mozilla Firefox (Version 99.0)

**Comment by bmatthieu3** [comment]
The binder link has been upgraded with the latest ipyaladin version. I am closing this issue for now, please do not hesitate to reopen it (or a new one) if you still have problem
