### ISSUE TITLE
Ipyaladin fails on jupyter notebook 

### ISSUE THREAD

**Issue by mohamed98gamal** [cds-astro/ipyaladin#36]
![IMG_20221025_223446_894.jpg](https://user-images.githubusercontent.com/116682971/197876525-31151400-dedb-4be8-af28-609c53815b5c.jpg))

**Comment by havok2063** [comment]
I am seeing the same error.  Run with the following packages in a Python 3.9 environment. 
```
ipyaladin                     0.1.9
ipykernel                     6.16.1
ipython                       8.4.0
ipywidgets                    8.0.2
jupyter                       1.0.0
jupyter_client                7.4.3
jupyter-console               6.4.4
jupyter_core                  4.11.2
jupyter-server                1.21.0
jupyterlab-pygments           0.2.2
jupyterlab-widgets            3.0.3
```

**Comment by bmatthieu3** [comment]
It should work with the version 0.1.11: pip install -U ipyaladin
to upgrade your ipyaladin.
Let me know if you still have the problem

**Comment by bmatthieu3** [comment]
I close the issue, do not hesitate to reopen a new one if the problem still persist on your side
