### ISSUE TITLE
Make ipyaladin running in JupyterLab

### ISSUE THREAD

**Issue by tboch** [cds-astro/ipyaladin#4]

**Comment by tboch** [comment]
This is developed in branch https://github.com/cds-astro/ipyaladin/tree/jupyterlab-support

**Comment by cdeil** [comment]
I tried with latest master (aa009c6d88ccfd2d25ea9d2b08c9dda201b9f55a) and got this error:
https://gist.github.com/cdeil/8d350e3e830b870c6af795814fa57369#file-gistfile1-txt-L159

Is this something you have to fix, or is my JupyterLab too old or some other issue on my side?

**Comment by athornton** [comment]
Is there any plan to release the JL extension as an NPM package, so we can just install it from npm rather than having to do a source build ?  If not...what needs to be done to make that happen?

**Comment by tboch** [comment]
@athornton : ipyaladin can be pip-installed. I'm not sure I understand your need, could you elaborate?

**Comment by athornton** [comment]
From the README:

```
To enable ipyaladin in JupyterLab:

$ git clone https://github.com/cds-astro/ipyaladin
$ cd ipyaladin/js
$ jupyter labextension install
```

It would be nice if I could get this without cloning the package, by having the lab extension published to npm as something like `@cds-astro/ipyaladin-jupyterlabextension`, so I can just `jupyter labexension install` it.

**Comment by athornton** [comment]
Is that sufficient elaboration?

**Comment by tboch** [comment]
yes, thank you @athornton , that's perfectly clear and I think that's a good idea.

Will do it.

**Comment by athornton** [comment]
Just bumping this issue, since AFAIK the extension has not been published to npm.

**Comment by athornton** [comment]
And again, now that JupyterLab 1.0 is released.

**Comment by bmatthieu3** [comment]
ipyaladin is much more supported inside jupyterlab from version 0.1.11. I close that issue. If you still experience problem, do not hesitate to reopen one.
