### ISSUE TITLE
1_Getting_Started.ipynb shows only a blue screen

### ISSUE THREAD

**Issue by JosephKarpinski** [cds-astro/ipyaladin#40]
1_Getting_Started.ipynb shows only a blue screen

<img width="1331" alt="Screen Shot 2022-12-14 at 2 45 55 PM" src="https://user-images.githubusercontent.com/37123616/207700243-7d893858-90fc-413d-b189-e1ecda610c23.png">

**Comment by bmatthieu3** [comment]
I broke it but now it should work (I target around the galactic center). So I close this issue
