### ISSUE TITLE
Unable to map Gaia DR3 Ra Dec values to an Aladin Display

### ISSUE THREAD

**Issue by JosephKarpinski** [cds-astro/ipyaladin#41]
Following example: 4_Importing_Tables.ipynb

<img width="1069" alt="Screen Shot 2022-12-15 at 4 36 52 PM" src="https://user-images.githubusercontent.com/37123616/207972568-1c9ba140-222a-4af0-a16e-2aa95dd56262.png">

I tried the same code using M45 Ra and Dec values returned from a Gaia DR3 query.

It looks like the coordinate systems do not match

<img width="1709" alt="Screen Shot 2022-12-15 at 4 26 54 PM" src="https://user-images.githubusercontent.com/37123616/207973267-b138113a-9c68-410e-8e58-2525c4fba60e.png">

Additional supporting data:

<img width="1724" alt="Screen Shot 2022-12-15 at 4 31 21 PM" src="https://user-images.githubusercontent.com/37123616/207973491-0281ced4-6068-46f7-918f-6fa472a44563.png">

<img width="1724" alt="Screen Shot 2022-12-15 at 4 32 50 PM" src="https://user-images.githubusercontent.com/37123616/207973546-b1f5ae7e-fc97-41dc-ab7b-6e3a081ce17c.png">

<img width="894" alt="Screen Shot 2022-12-15 at 4 33 25 PM" src="https://user-images.githubusercontent.com/37123616/207973584-e57c369d-905b-4772-9872-ef715ca830a3.png">

<img width="894" alt="Screen Shot 2022-12-15 at 4 33 47 PM" src="https://user-images.githubusercontent.com/37123616/207973615-9da281db-a78c-468a-ad90-34e4d8a704c7.png">

<img width="894" alt="Screen Shot 2022-12-15 at 4 34 07 PM" src="https://user-images.githubusercontent.com/37123616/207974634-c7b73a9b-42e1-4dfa-b8fa-b731d21bd948.png">

<img width="894" alt="Screen Shot 2022-12-15 at 4 34 21 PM" src="https://user-images.githubusercontent.com/37123616/207974638-99b8c7b8-75a6-44a9-b3dd-1d885363eb30.png">

<img width="894" alt="Screen Shot 2022-12-15 at 4 35 41 PM" src="https://user-images.githubusercontent.com/37123616/207974636-54911c32-8bc8-4ad4-bdde-e0de30cf1c4a.png">

**Comment by ManonMarchand** [comment]
@bmatthieu3 added info : smaller query size gives the correct output

**Comment by JosephKarpinski** [comment]
Well, I tracked the issue down. It appears to be related to using Ra and Dec array values as shown in the "Display Astropy created from scratch" example, shown above. This appears to work for a small sample, but increasing the number of star positions quickly turns the display into a straight line mapping. Supporting code:
<img width="1247" alt="Screen Shot 2022-12-18 at 10 42 00 AM" src="https://user-images.githubusercontent.com/37123616/208308235-5d9b4dad-ec4b-4d8b-980d-7ae3d8494423.png">
<img width="1247" alt="Screen Shot 2022-12-18 at 10 42 19 AM" src="https://user-images.githubusercontent.com/37123616/208308236-8878176b-d4f7-4f07-9e62-06746b867ab5.png">
<img width="1247" alt="Screen Shot 2022-12-18 at 10 42 43 AM" src="https://user-images.githubusercontent.com/37123616/208308237-94094248-aa8f-4acc-a7b1-1be5254ac783.png">
<img width="2041" alt="Screen Shot 2022-12-18 at 10 43 23 AM" src="https://user-images.githubusercontent.com/37123616/208308239-b128f4fe-0705-4028-9a34-24ff12073e65.png">



Directly using Python DataFrame values for Ra and Dec works;

<img width="2041" alt="Screen Shot 2022-12-18 at 10 45 43 AM" src="https://user-images.githubusercontent.com/37123616/208308248-09cd2fb9-5808-49a8-bd45-cc5cee7e4d46.png">

**Comment by tboch** [comment]
Hi,
You are sorting ra and dec values, and providing the sorted lists to ipyaladin.
Hence the result and the straight line!

**Comment by JosephKarpinski** [comment]
I should of seen it!
Always use sort.tolist() and never gave it a second thought when extracting and combining Ra and Dec values.
User error!
Thank you!

Please close!

Sent from my iPhone

On Dec 19, 2022, at 2:47 AM, Thomas Boch ***@***.***> wrote:

﻿

Hi,
You are sorting ra and dec values, and providing the sorted lists to ipyaladin.
Hence the result and the straight line!
