### ISSUE TITLE
Development install instructions slightly incorrect

### ISSUE THREAD

**Issue by jbrinchmann** [cds-astro/ipyaladin#48]
Hi, 

I was trying to install following the development install instructions in the README, but I realised that this omits building the Javascript library so in the end I got several errors. Comparing to the compile.sh script, it seems that 
```
cd js
npm install
cd ..
```
is missing. With those commands everything seems to be working.

**Comment by ManonMarchand** [comment]
Hello! Thanks for spotting that, we'll change the instructions

**Comment by ManonMarchand** [comment]
Will be fixed with next release (see PR opened on dev branch)
