### ISSUE TITLE
Plot a mocpy object

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/ipyaladin#49]
Add possibility to load a moc from a mocpy object: `ipyaladin.add_moc(mon_moc, adjust_view=True)`

**Comment by ManonMarchand** [comment]
With a possibility to make the widget adapt the view on the MOC (as in MOC.wcs())

**Comment by ManonMarchand** [comment]
Thinking again about this issue, we should wait that MOCpy works in Jupyterlite before adding it as a dependency for ipyaladin
