### ISSUE TITLE
Is it possible to save jpg/png programmatically?

### ISSUE THREAD

**Issue by cylammarco** [cds-astro/ipyaladin#52]
When I use `get_JPEG_thumbnail()`, an image pops up in a new tab. Is it possible to programmatically save the image instead of having a pop-up?

**Comment by ManonMarchand** [comment]
Hello and thanks for your idea! 
For now it is not possible but I think we can do this when we solve this other feature request #15

**Comment by ManonMarchand** [comment]
Notes for later: could do something with an optional dependency to https://astroquery.readthedocs.io/en/latest/hips2fits/hips2fits.html ?
