### ISSUE TITLE
Implement the right click

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/ipyaladin#55]
The **super cool** right click menu of aladin-lite is missing in ipyaladin

**Comment by ManonMarchand** [comment]
Will appear at the next aladin-lite release

**Comment by bmatthieu3** [comment]
In my laptop it does not show on jupyterlite but in the aladin lite previewer yes (aladin lite has been deployed). I think it is a bug on ipyaladin. Somehow the rightclick event seems to be lost before coming to the eyes of aladin lite.

**Comment by ManonMarchand** [comment]
Does ipyaladin point to the main branch or the dev branch? I thought this was the issue was coming from there. 

If not, I'll reopen the issue and mark it as a bug I guess?

**Comment by bmatthieu3** [comment]
It fetches the version deployed (same as the aladin lite previewer: https://aladin.cds.unistra.fr/AladinLite/). The js file deployed is located here: https://aladin.u-strasbg.fr/AladinLite/api/v3/latest/aladin.js

When instancing an Aladin object, one should set the `show_context_menu: True`, but on my laptop, after that, rightclicking does not make the menu appear.

**Comment by ManonMarchand** [comment]
Ahah c'était facile 
![image](https://github.com/cds-astro/ipyaladin/assets/16650466/deec91e6-2b17-43e0-a060-fbf81aac0bfe)
Je push un commit dans develop

**Comment by bmatthieu3** [comment]
Ahah excellent!
