### ISSUE TITLE
Bounding box measured in pixel sizes (vs RA/DEC)

### ISSUE THREAD

**Issue by SultanOrazbayev** [cds-astro/ipyaladin#64]
It's possible to add a bounding box/shape using  `add_overlay_from_stcs` method on `ipyaladin`. However this requires specifying the coordinates using RA/DEC. Is it possible to specify the bounding box coordinates using pixels?

```python
from ipyaladin import Aladin
a = Aladin(target="M 51", fov=1.2)
a.add_overlay_from_stcs(
    "Polygon ICRS 202.63748 47.24951 202.46382 47.32391 202.46379 47.32391 202.45459 47.32391 202.34527 47.20597 202.34527 47.20596 202.34529 47.19710 202.51870 47.12286 202.52789 47.12286 202.52791 47.12286 202.63746 47.24063 202.63749 47.24949\nPolygon J2000 202.74977 47.36958 202.57592 47.44415 202.57585 47.44416 202.56666 47.44416 202.45683 47.32632 202.45683 47.31746 202.63051 47.24302 202.63970 47.24302 202.74978 47.36069 202.74982 47.36955\nPolygon J2000 202.52540 47.12904 202.35192 47.20325 202.34273 47.20325 202.23391 47.08518 202.23395 47.07633 202.23398 47.07630 202.40715 47.00227 202.40721 47.00226 202.41640 47.00226 202.52539 47.12018",
    {"color": "red"},
)
a
```

**Comment by ManonMarchand** [comment]
Hello and thanks for opening the ticket :slightly_smiling_face: 

This is not possible yet, but it is a good idea for a feature! We'll have a look at this. 

Notes for implementation: 

- add world2pix and pix2world to user api, 
- check the current frame
- check it works also when height changes

**Comment by SultanOrazbayev** [comment]
Thank you for the quick response!

From reading more about this, I see that astropy has some utils for converting degree to pixel (and back). However, they require WCS info, which can be loaded from FITS. In case of `ipyaladin` can you tell me which WCS is used?

**Comment by ManonMarchand** [comment]
Hello, 

There is an experimental branch `feature-export-wcs` if you want to try it (clone the repo, switch to branch and `pip install .`)

The use is documented in `2_Base_commands.ipynb` 

(looks like this)

```python
from ipyaladin import Aladin
aladin = Aladin()
aladin
```
```python
aladin.update_WCS()
```
```python
aladin.wcs # returns a dictionnary with the WCS information
```

Won't merge yet due to two limitations:

- the information is wrong for projections other than SIN and galactic coordinate system for now (will be solved when cds-astro/aladin-lite#119) is merged
- for now we cannot put the update and the print in the same cell. There is an issue in execution between javascript code and python one that we'll need to understand

**Comment by SultanOrazbayev** [comment]
This is very useful, thank you very much, @ManonMarchand !

**Comment by ManonMarchand** [comment]
No worries
Some projections are still buggy but we're approaching a merge upstream :muscle:

**Comment by SultanOrazbayev** [comment]
Thank you, @ManonMarchand !

**Comment by ManonMarchand** [comment]
Was done by @Xen0Xys ;) 
You now have access to the WCS, see example 11. This should allow you to retrieve what you need, but don't hesitate to open a new issue if it does not work.
