### ISSUE TITLE
Add configurable widgets-based controls

### ISSUE THREAD

**Issue by tboch** [cds-astro/ipyaladin#7]
Have at least:

- [ ] option to add a side bar with a pre selected list of HIPS as in planet explorer 
- [x] an opacity slider
- [ ] a catalogue controller as in the right side of aladin-lite

**Comment by ManonMarchand** [comment]
- option to add a side bar with a pre selected list of HIPS as in planet explorer ?

**Comment by ManonMarchand** [comment]
Add fetch to mocserver in initialize (on JS side)
