### ISSUE TITLE
Failed to load model class AladinModel from module ipyaladin 

### ISSUE THREAD

**Issue by JosephKarpinski** [cds-astro/ipyaladin#72]
Failed to load model class AladinModel from module ipyaladin 

Updated to from version 0.2.1 to 0.2.5 same issue under Jupyter notebook 

![Screenshot 2024-01-31 at 9 57 37 AM](https://github.com/cds-astro/ipyaladin/assets/37123616/770b055f-9ee2-4bf4-a8bb-9b7052d35192)

![Screenshot 2024-01-31 at 10 05 24 AM](https://github.com/cds-astro/ipyaladin/assets/37123616/aa06de7d-600f-440f-9cf2-0bceb4a26f88)

![Screenshot 2024-01-31 at 10 08 39 AM](https://github.com/cds-astro/ipyaladin/assets/37123616/2134bf70-7471-455f-a53e-4746b5fc48f0)

**Comment by ManonMarchand** [comment]
Hi and thanks for reporting!
I cannot reproduce the issue though.

In a fresh python 3.9.12 environment, if I do : 

```
pip install ipyaladin
pip install notebook
python -m notebook
```

I obtain a working widget. Could you try this? 

If it is still broken, could you also share what browser you use and the content of the console when executing the cell with the widget (opened with `ctrl` `shift` `j` on firefox and `ctrl` `maj` `i` on chrome)

**Comment by JosephKarpinski** [comment]
Got it to work using Chrome instead of Safari on an M1 iMac running Sonoma 14.2.1.
Please close.

**Comment by ManonMarchand** [comment]
@bmatthieu3 : can you try on your mac with Safari ?

**Comment by bmatthieu3** [comment]
@ManonMarchand @JosephKarpinski - I did a new empty virtualenv and run it with safari but I could not reproduce the error i.e. it works for me on my safari Version 17.2, mac M1 Sonoma 14.2 (23C64)
Here is my history of command:
```bash
 virtualenv -p=python3 ipyalenv
 source ipyalenv/bin/activate
 python -m pip install ipyaladin
 python -m pip install notebook
 python -m notebook
```
When running the notebook, I selected my python3 ipykernel
