### ISSUE TITLE
Allow the list of keyword options (CatalogOptions, HiPSOptions, MOCOptions, ...) passed to be case insensitive

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/ipyaladin#77]
To be more pythonic friendly. Example: Python users would be able to pass min_cut (python way) and/or minCut (js way) https://cds-astro.github.io/aladin-lite/global.html#ImageSurveyOptions through ipyaladin API

**Comment by ManonMarchand** [comment]
See the implementation of add_table where the options are not snakecase
