### ISSUE TITLE
Aladin Lite version for positionChanged event callback argument

### ISSUE THREAD

**Issue by Xen0Xys** [cds-astro/ipyaladin#87]
When using the callback argument "position" in the positionChanged event, the position is given as a RA and a DEC depending of the selected frame and not ICRS. This behavior will be changed in a future version, the code do not need any change for this to work.
But currently, using a galactic frame can cause bugs.

**Comment by bmatthieu3** [comment]
I close this. Now I give icrs position in positionChanged callback. Thanks for having seen that @Xen0Xys
